### ISSUE TITLE
mex functions fail to compile with MATLAB R2018a

### ISSUE THREAD

**Issue by simgunz** [FastNFT/FNFT#10]
The following error occurs when compiling the mex functions using MATLAB R2018a
```
set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c99 -Wall -Wextra -pedantic -Werror=implicit-function-declaration")
```

Removing the gcc flag `-Werror=implicit-function-declaration` makes it compile fine, but when the function is called from MATLAB throws the following error:
```
Invalid MEX-file '/media/dataHD/downloads/browser/FNFT/matlab/mex_fnft_kdvv.mexa64': /media/dataHD/downloads/browser/FNFT/matlab/mex_fnft_kdvv.mexa64:
undefined symbol: mxGetPiIsDeprecated.
```

**Comment by wahls** [comment]
Thanks for the report. Will try to fix it on Monday.

**Comment by wahls** [comment]
I made a new release (v0.1.1) which should fix this and a few other issues. Please let me know if it works.

The issue was that Matlab R2018a introduces a new "Interleaved Complex API" to pass complex data to mex files. By default the mex command is still using the old API, but since cmake is not using the mex command to build mex files, it accidentally tried to compile with the new API instead. Adding a "-DMEX_DOUBLE_HANDLE" switch in the cmake file solved the issue, which lets us use the old API even without using the mex command (see "MEX Functions: Release-specific build options" in the release notes for Matlab R2018a).

PS: If cmake does not find Matlab R2018a on MacOS, try passing the option  "-DMatlab_ROOT_DIR=/Applications/MATLAB_R2018a.app".

**Comment by simgunz** [comment]
I confirm it compiles and runs fine now. Thanks.

**Comment by wahls** [comment]
Great. I am closing the issue.
