### ISSUE TITLE
Thread_local detected but not supported by C99

### ISSUE THREAD

**Issue by marbre** [FastNFT/FNFT#19]
CMake is detecting Thread_local:
```
-- The C compiler identification is GNU 6.4.0
[..]
-- Performing Test HAVE__THREAD_LOCAL
-- Performing Test HAVE__THREAD_LOCAL - Success
```

Anyway, C99 does not support it:
```
[  0%] Building C object CMakeFiles/fnft.dir/src/fnft_errwarn.c.o
/home/brehler/Development/FNFT/src/fnft_errwarn.c:44:1: warning: ISO C99 does not support ‘_Thread_local’ [-Wpedantic]
 _Thread_local
```

**Comment by wahls** [comment]
We are trying to make FNFT C99 compliant. Normally all warnings are fixed, but since C99 does not support thread-local storage there is no obvious way to fix this one.

So this is the one warning that does not get fixed. If a compiler really does not support the keyword, FNFT will simply be build without using it. (It is used in one place only anyway.)

**Comment by marbre** [comment]
One could actually set `HAVE__THREAD_LOCAL` to `false` in the case that `gcc -std=c99` is used as compiler. However, the _test structure_ should be modified as one still should check if `HAVE___THREAD` is available in that case. I could work on that if desired.

**Comment by marbre** [comment]
Close due to the merge of #23.
